export const adminCopy = {
  title: "Admin",
  dashboard: "Paneli",
  products: "Produktet",
  categories: "Kategoritë",
  brands: "Markat",
  orders: "Porositë",
  discounts: "Zbritjet",
  content: "Përmbajtja",
  settings: "Cilësimet",
  signOut: "Dil",
  signedInAs: "I kyçur si",
  placeholder: "Kjo faqe ndërtohet në njësinë e radhës.",
  dashboardBody: "Mirë se vini në panelin e Sanem.",
  productNew: "Produkt i ri",
  productEdit: "Ndrysho produktin",
  productSave: "Ruaj",
  productSaving: "Duke ruajtur…",
  productSearch: "Kërko emrin ose slug…",
  productFilterStatus: "Statusi",
  productFilterBrand: "Marka",
  productFilterCategory: "Kategoria",
  productAll: "Të gjitha",
  productBulkActivate: "Aktivizo",
  productBulkArchive: "Arkivo",
  productStatusDraft: "Draft",
  productStatusActive: "Aktiv",
  productStatusArchived: "Arkivuar",
  productName: "Emri",
  productSlug: "Slug",
  productShort: "Përshkrim i shkurtër",
  productDescription: "Përshkrimi (markdown)",
  productPreview: "Parapamja",
  productOptions: "Opsionet (max 2)",
  productOptionName: "Emri i opsionit",
  productOptionValues: "Vlerat (ndara me presje)",
  productAddOption: "Shto opsion",
  productVariants: "Variantet",
  productSku: "SKU",
  productPrice: "Çmimi (cent)",
  productCompareAt: "Çmimi krahasues (cent)",
  productStock: "Stoku",
  productDefault: "Parazgjedhur",
  productFlags: "Flamuj",
  productIsNew: "E re",
  productIsBestSeller: "Më e shitura",
  productUnit: "Njësia",
  productUnitAmount: "Sasia",
  productUnitLabel: "Etiketa",
  productRelated: "Të ngjashme (ID, ndara me presje)",
  productSeoTitle: "SEO titulli",
  productSeoDescription: "SEO përshkrimi",
  productImagesHint: "Ngarko imazhe; alt është i detyrueshëm. Max 10 MB.",
  productImages: "Imazhet",
  productImagesAlt: "Teksti alt",
  productImagesAltRequired: "Shkruaj tekstin alt para ngarkimit.",
  productImagesDrop: "Tërhiq një foto këtu, ose zgjidh një skedar.",
  productImagesPick: "Zgjidh foto",
  productImagesUploading: "Duke ngarkuar…",
  productImagesRemove: "Hiq",
  productImagesTooLarge: "Skedari është shumë i madh (max 10 MB).",
  productImagesUploadFail: "Ngarkimi dështoi.",
  productImagesSaveFirst: "Ruaj produktin fillimisht, pastaj ngarko imazhe.",
  productStockSave: "Ruaj stokun",
  productStockChanged: "Stoku ndryshoi — ringarko faqen.",
  productSaveOk: "Produkti u ruajt.",
  productSaveFail: "Ruajtja dështoi.",
  productColName: "Emri",
  productColStatus: "Statusi",
  productColStock: "Stoku",
  productColPrice: "Çmimi",
  productColUpdated: "Përditësuar",
  productEmpty: "Nuk ka produkte.",
} as const;

export const adminNav = [
  { href: "/admin", label: adminCopy.dashboard },
  { href: "/admin/products", label: adminCopy.products },
  { href: "/admin/categories", label: adminCopy.categories },
  { href: "/admin/brands", label: adminCopy.brands },
  { href: "/admin/orders", label: adminCopy.orders },
  { href: "/admin/discounts", label: adminCopy.discounts },
  { href: "/admin/content", label: adminCopy.content },
  { href: "/admin/settings", label: adminCopy.settings },
] as const;
