export const adminCopy = {
  title: "Admin",
  dashboard: "Paneli",
  products: "Produktet",
  categories: "Kategoritë",
  brands: "Markat",
  orders: "Porositë",
  discounts: "Zbritjet",
  content: "Përmbajtja",
  settings: "Cilësimet",
  signOut: "Dil",
  signedInAs: "I kyçur si",
  placeholder: "Kjo faqe ndërtohet në njësinë e radhës.",
  dashboardBody: "Mirë se vini në panelin e Sanem.",
  dashToday: "Sot",
  dashDays7: "7 ditët",
  dashDays30: "30 ditët",
  dashOrders: "Porosi",
  dashRevenue: "Të ardhura",
  dashAverage: "Mesatarja",
  dashLatestOrders: "Porositë e fundit",
  dashLowStock: "Stok i ulët",
  dashLowStockEmpty: "Asnjë produkt me stok ≤ 5.",
  dashColNumber: "Numri",
  dashColCustomer: "Klienti",
  dashColTotal: "Totali",
  dashColStatus: "Statusi",
  dashColStock: "Stoku",
  dashColProduct: "Produkti",
  dashEmptyOrders: "Nuk ka porosi ende.",
  productNew: "Produkt i ri",
  productEdit: "Ndrysho produktin",
  productSave: "Ruaj",
  productSaving: "Duke ruajtur…",
  productSearch: "Kërko emrin ose slug…",
  productFilterStatus: "Statusi",
  productFilterBrand: "Marka",
  productFilterCategory: "Kategoria",
  productAll: "Të gjitha",
  productBulkActivate: "Aktivizo",
  productBulkArchive: "Arkivo",
  productStatusDraft: "Draft",
  productStatusActive: "Aktiv",
  productStatusArchived: "Arkivuar",
  productName: "Emri",
  productSlug: "Slug",
  productShort: "Përshkrim i shkurtër",
  productDescription: "Përshkrimi (markdown)",
  productPreview: "Parapamja",
  productOptions: "Opsionet (max 2)",
  productOptionName: "Emri i opsionit",
  productOptionValues: "Vlerat (ndara me presje)",
  productAddOption: "Shto opsion",
  productVariants: "Variantet",
  productSku: "SKU",
  productPrice: "Çmimi (cent)",
  productCompareAt: "Çmimi krahasues (cent)",
  productStock: "Stoku",
  productDefault: "Parazgjedhur",
  productFlags: "Flamuj",
  productIsNew: "E re",
  productIsBestSeller: "Më e shitura",
  productUnit: "Njësia",
  productUnitAmount: "Sasia",
  productUnitLabel: "Etiketa",
  productRelated: "Të ngjashme (ID, ndara me presje)",
  productSeoTitle: "SEO titulli",
  productSeoDescription: "SEO përshkrimi",
  productImagesHint: "Ngarko imazhe; alt është i detyrueshëm. Max 10 MB.",
  productImages: "Imazhet",
  productImagesAlt: "Teksti alt",
  productImagesAltRequired: "Shkruaj tekstin alt para ngarkimit.",
  productImagesDrop: "Tërhiq një foto këtu, ose zgjidh një skedar.",
  productImagesPick: "Zgjidh foto",
  productImagesUploading: "Duke ngarkuar…",
  productImagesRemove: "Hiq",
  productImagesTooLarge: "Skedari është shumë i madh (max 10 MB).",
  productImagesUploadFail: "Ngarkimi dështoi.",
  productImagesSaveFirst: "Ruaj produktin fillimisht, pastaj ngarko imazhe.",
  productStockSave: "Ruaj stokun",
  productStockChanged: "Stoku ndryshoi — ringarko faqen.",
  productSaveOk: "Produkti u ruajt.",
  productSaveFail: "Ruajtja dështoi.",
  productColName: "Emri",
  productColStatus: "Statusi",
  productColStock: "Stoku",
  productColPrice: "Çmimi",
  productColUpdated: "Përditësuar",
  productEmpty: "Nuk ka produkte.",
  taxSave: "Ruaj",
  taxSaving: "Duke ruajtur…",
  taxSaved: "U ruajt.",
  taxSaveFail: "Ruajtja dështoi.",
  taxName: "Emri",
  taxSlug: "Slug",
  taxParent: "Prindi",
  taxParentNone: "— Rrënja —",
  taxActive: "Aktive",
  taxOrder: "Renditja",
  taxMoveUp: "Lart",
  taxMoveDown: "Poshtë",
  taxArchive: "Arkivo",
  taxDelete: "Fshi",
  taxInUse: "Ka produkte — nuk fshihet. Arkivoje.",
  taxNewCategory: "Kategori e re",
  taxEditCategory: "Ndrysho kategorinë",
  taxNewBrand: "Markë e re",
  taxEditBrand: "Ndrysho markën",
  taxDescription: "Përshkrimi",
  taxProducts: "Produkte",
  taxSeoTitle: "SEO titulli",
  taxSeoDescription: "SEO përshkrimi",
  taxInactive: "Jo aktive",
  orderSearch: "Kërko numrin, email ose telefon…",
  orderFilterStatus: "Statusi",
  orderFilterPayment: "Pagesa",
  orderFilterFrom: "Nga data",
  orderFilterTo: "Deri më",
  orderAll: "Të gjitha",
  orderExportCsv: "Eksporto CSV",
  orderEmpty: "Nuk ka porosi.",
  orderColNumber: "Numri",
  orderColDate: "Data",
  orderColCustomer: "Klienti",
  orderColTotal: "Totali",
  orderColStatus: "Statusi",
  orderColPayment: "Pagesa",
  orderStatusPending: "Në pritje",
  orderStatusConfirmed: "Konfirmuar",
  orderStatusShipped: "Dërguar",
  orderStatusDelivered: "Dorëzuar",
  orderStatusCancelled: "Anuluar",
  orderPayCodDue: "Para në dorë",
  orderPayAwaiting: "Në pritje të pagesës",
  orderPayPaid: "Paguar",
  orderPayFailed: "Dështuar",
  orderPayRefunded: "Rimbursuar",
  orderDetail: "Detajet e porosisë",
  orderLines: "Artikujt",
  orderAddresses: "Adresat",
  orderDelivery: "Dërgesa",
  orderBilling: "Faturimi",
  orderTotals: "Totalet",
  orderSubtotal: "Nëntotali",
  orderDiscount: "Zbritja",
  orderDeliveryFee: "Transporti",
  orderTotal: "Totali",
  orderPayment: "Pagesa",
  orderBankTx: "ID e transaksionit",
  orderBankLast4: "Kartë (4 shifrat e fundit)",
  orderBankPortal: "Portali i bankës (rimbursime)",
  orderTimeline: "Kronologjia",
  orderInternalNote: "Shënim i brendshëm",
  orderNoteSave: "Ruaj shënimin",
  orderStatusChange: "Ndrysho statusin",
  orderStatusNote: "Shënim (opsional)",
  orderStatusSubmit: "Përditëso",
  orderMarkPaid: "Shëno si të paguar",
  orderPrint: "Printo",
  orderBack: "Te porositë",
  orderSaveOk: "U ruajt.",
  orderSaveFail: "Ruajtja dështoi.",
  orderPrintTitle: "Fatura / lista e paketimit",
  discountNew: "Kod i ri",
  discountEdit: "Ndrysho kodin",
  discountCode: "Kodi",
  discountType: "Lloji",
  discountTypePercent: "Përqindje",
  discountTypeFixed: "Shumë fikse (cent)",
  discountTypeFreeDelivery: "Transport falas",
  discountValue: "Vlera",
  discountMinSubtotal: "Minimumi (cent)",
  discountStartsAt: "Fillon",
  discountEndsAt: "Mbaron",
  discountUsageLimit: "Limiti i përdorimeve",
  discountUsageUnlimited: "Pa limit",
  discountUsedCount: "Përdorime",
  discountActive: "Aktiv",
  discountInactive: "Jo aktiv",
  discountSave: "Ruaj",
  discountSaving: "Duke ruajtur…",
  discountSaved: "U ruajt.",
  discountSaveFail: "Ruajtja dështoi.",
  discountTurnOff: "Çaktivizo",
  discountTurnOn: "Aktivizo",
  discountEmpty: "Nuk ka kode zbritjeje.",
  discountCodeLocked: "Kodi nuk ndryshohet pas krijimit.",
  contentHero: "Hero slides",
  contentPromo: "Blloqe promo",
  contentBrandStrip: "Renditja e brand strip",
  contentSlideTitle: "Titulli",
  contentSlideSubtitle: "Nëntitulli",
  contentSlideLink: "Lidhja",
  contentSlideOrder: "Renditja",
  contentSlideActive: "Aktiv",
  contentSlideImage: "Imazhi",
  contentAddSlide: "Shto slide",
  contentAddPromo: "Shto promo",
  contentPromoTitle: "Titulli",
  contentPromoBody: "Teksti",
  contentPromoLink: "Lidhja",
  contentSave: "Ruaj përmbajtjen",
  contentSaving: "Duke ruajtur…",
  contentSaved: "U ruajt.",
  contentSaveFail: "Ruajtja dështoi.",
  contentUploadFail: "Ngarkimi dështoi.",
  contentBrandIds: "ID e produkteve (një për rresht)",
  settingsDelivery: "Metodat e dërgesës",
  settingsPayment: "Metodat e pagesës",
  settingsCompany: "Kompania",
  settingsOrdersInbox: "Inbox i porosive",
  settingsOrderPrefix: "Prefiksi i numrit",
  settingsFreeOver: "Transport falas mbi (cent)",
  settingsPrice: "Çmimi (cent)",
  settingsDays: "Kohëzgjatja",
  settingsLabel: "Etiketa",
  settingsActive: "Aktive",
  settingsSave: "Ruaj cilësimet",
  settingsSaving: "Duke ruajtur…",
  settingsSaved: "U ruajt.",
  settingsSaveFail: "Ruajtja dështoi.",
  settingsNewsletterCsv: "Eksporto newsletter CSV",
  settingsCompanyName: "Emri",
  settingsCompanyEmail: "Email",
  settingsCompanyPhone: "Telefoni",
  settingsCompanyAddress: "Adresa",
  settingsCompanyIban: "IBAN",
} as const;

export const adminNav = [
  { href: "/admin", label: adminCopy.dashboard },
  { href: "/admin/products", label: adminCopy.products },
  { href: "/admin/categories", label: adminCopy.categories },
  { href: "/admin/brands", label: adminCopy.brands },
  { href: "/admin/orders", label: adminCopy.orders },
  { href: "/admin/discounts", label: adminCopy.discounts },
  { href: "/admin/content", label: adminCopy.content },
  { href: "/admin/settings", label: adminCopy.settings },
] as const;
