export const shopCopy = {
  fromPrice: "Nga:",
  inStock: "Në stok",
  outOfStock: "Jashtë stoku",
  isNew: "E re",
  isBestSeller: "Më e shitura",
  selectOptions: "Përzgjidhni mundësi",
  breadcrumbHome: "Kreu",
  sortLabel: "Rendit",
  sortNewest: "Më të rejat",
  sortPriceAsc: "Çmimi: ulët → lart",
  sortPriceDesc: "Çmimi: lart → ulët",
  sortBestSellers: "Më të shiturat",
  emptyCategory: "Nuk ka produkte në këtë kategori ende.",
  paginationPrev: "Faqja e mëparshme",
  paginationNext: "Faqja e radhës",
  paginationPage: "Faqja",
  resultCount: "produkte",
  addToCart: "Shtoje në shportë",
  addToCartAdding: "Duke shtuar…",
  addToCartToast: "U shtua në shportë.",
  quantity: "Sasia",
  cartTitle: "Shporta",
  cartEmpty: "Shporta juaj është bosh.",
  cartContinue: "Vazhdo blerjet",
  cartCheckout: "Vazhdo te pagesa",
  cartSubtotal: "Nëntotali",
  cartDiscount: "Zbritja",
  cartDeliveryAtCheckout: "Transporti llogaritet në arkë.",
  cartDiscountPlaceholder: "Kodi i zbritjes",
  cartDiscountApply: "Apliko",
  cartRemove: "Hiq",
  cartUndo: "Zhbëj",
  cartRemovedToast: "Produkti u hoq nga shporta.",
  cartQtyDecrease: "Ul sasinë",
  cartQtyIncrease: "Rrit sasinë",
  cartOpen: "Hap shportën",
  cartFreeDeliveryAdd: "Shtoni {amount} për transport falas.",
  cartFreeDeliveryReached: "Transporti falas është gati.",
  cartViewFull: "Shiko shportën",
  deliveryHeading: "Dorëzimi",
  deliveryFee: "Tarifa e transportit",
  deliveryFreeOver: "Transport falas mbi",
  deliveryTime: "Afati",
  paymentCod: "Para në dorë",
  descriptionHeading: "Përshkrimi",
  categoriesHeading: "Kategoritë",
  relatedHeading: "Të ngjashme",
  searchPlaceholder: "Kërko produkte…",
  searchEmpty: "Nuk u gjet asnjë produkt.",
  searchHint: "Shkruaj të paktën 2 shkronja.",
  searchPageTitle: "Kërkimi",
  searchBrowseCategories: "Shfleto kategoritë",
  cartMerged: "Rreshtat e njëjtë u bashkuan.",
  cartQtyClamped: "Sasia u ul sipas stokut.",
  cartProductUnavailable: "Produkti nuk është më i disponueshëm.",
  cartVariantMissing: "Varianti nuk u gjet.",
  discountInvalid: "Kodi nuk është i vlefshëm.",
  discountExpired: "Kodi ka skaduar.",
  discountMinimum: "Minimumi i porosisë nuk është arritur.",
  discountLimit: "Kodi është përdorur plotësisht.",
  checkoutTitle: "Arkë",
  checkoutEmptyRedirect: "Shporta është bosh — shto produkte para pagesës.",
  checkoutEmail: "E-mail",
  checkoutRecipient: "Emri i marrësit",
  checkoutAddress: "Adresa",
  checkoutCity: "Qyteti",
  checkoutCitySearch: "Kërko qytetin…",
  checkoutCityEmpty: "Nuk u gjet asnjë qytet.",
  checkoutPostal: "Kodi postar (opsional)",
  checkoutPhone: "Telefoni",
  checkoutPhoneHint: "Formati: +383 49 123 456",
  checkoutCountry: "Shteti",
  checkoutCountryKosovo: "Kosovë",
  checkoutBillingSame: "Adresa e faturimit është e njëjtë me dorëzimin",
  checkoutBillingHeading: "Adresa e faturimit",
  checkoutDeliveryMethod: "Mënyra e dorëzimit",
  checkoutPaymentMethod: "Mënyra e pagesës",
  checkoutNewsletter: "Dëshiroj të marr oferta me email",
  checkoutTerms: "Pranoj kushtet e përdorimit dhe politikën e privatësisë",
  checkoutTermsLink: "Kushtet",
  checkoutPrivacyLink: "Privatësia",
  checkoutSubmit: "Bëje porosinë",
  checkoutSubmitSoon: "Porosia do të dërgohet në hapin e radhës.",
  checkoutSummary: "Përmbledhja",
  checkoutTotal: "Totali",
  checkoutDeliveryLine: "Transporti",
  checkoutFree: "Falas",
  checkoutDiscountCode: "Kodi i zbritjes",
  fieldRequired: "Ky fushë është e detyrueshme.",
  fieldEmail: "Shkruaj një email të vlefshëm.",
  fieldPhone: "Përdor +383 dhe 8 shifra (p.sh. +383 49 123 456).",
  fieldCity: "Zgjidh një qytet nga lista.",
  fieldTerms: "Duhet të pranosh kushtet për të vazhduar.",
  fieldTurnstile: "Plotëso verifikimin e sigurisë.",
  optionLabels: {
    size: "Mililitra",
    concentration: "Përqendrimi",
  } as Record<string, string>,
} as const;
