export const shopCopy = {
  fromPrice: "Nga:",
  inStock: "Në stok",
  outOfStock: "Jashtë stoku",
  isNew: "E re",
  isBestSeller: "Më e shitura",
  selectOptions: "Përzgjidhni mundësi",
  breadcrumbHome: "Kreu",
  sortLabel: "Rendit",
  sortNewest: "Më të rejat",
  sortPriceAsc: "Çmimi: ulët → lart",
  sortPriceDesc: "Çmimi: lart → ulët",
  sortBestSellers: "Më të shiturat",
  emptyCategory: "Nuk ka produkte në këtë kategori ende.",
  paginationPrev: "Faqja e mëparshme",
  paginationNext: "Faqja e radhës",
  paginationPage: "Faqja",
  resultCount: "produkte",
  addToCart: "Shtoje në shportë",
  addToCartSoon: "Së shpejti — shporta ende nuk është gati.",
  quantity: "Sasia",
  deliveryHeading: "Dorëzimi",
  deliveryFee: "Tarifa e transportit",
  deliveryFreeOver: "Transport falas mbi",
  deliveryTime: "Afati",
  paymentCod: "Para në dorë",
  descriptionHeading: "Përshkrimi",
  categoriesHeading: "Kategoritë",
  relatedHeading: "Të ngjashme",
  searchPlaceholder: "Kërko produkte…",
  searchEmpty: "Nuk u gjet asnjë produkt.",
  searchHint: "Shkruaj të paktën 2 shkronja.",
  searchPageTitle: "Kërkimi",
  searchBrowseCategories: "Shfleto kategoritë",
  optionLabels: {
    size: "Mililitra",
    concentration: "Përqendrimi",
  } as Record<string, string>,
} as const;
