export const shopCopy = {
  fromPrice: "Nga:",
  inStock: "Në stok",
  outOfStock: "Jashtë stoku",
  isNew: "E re",
  isBestSeller: "Më e shitura",
  selectOptions: "Përzgjidhni mundësi",
  breadcrumbHome: "Kreu",
  sortLabel: "Rendit",
  sortNewest: "Më të rejat",
  sortPriceAsc: "Çmimi: ulët → lart",
  sortPriceDesc: "Çmimi: lart → ulët",
  sortBestSellers: "Më të shiturat",
  emptyCategory: "Nuk ka produkte në këtë kategori ende.",
  paginationPrev: "Faqja e mëparshme",
  paginationNext: "Faqja e radhës",
  paginationPage: "Faqja",
  resultCount: "produkte",
} as const;
